org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableJetifier=false
kotlin.code.style=official
WHISPER_CPP_API_KEY=D0yoUkn0wwho@mI%cAtCHm31fUcan
CAPSOLVER_API_KEY=CAP-D5903264575AE0571295C9D7A21B097F
BLS_USER=67sixseven
BLS_PASS=67766776_
PHONE_REP_API_KEY=522387e25611ffb108e7b3bca1c6b98c
BLACKLIST_API_KEY=k3yb11acklist$eller-aslwisdn435hu234iohh
